name: On Push

on: push

jobs:
	lint-and-test:
		runs-on: ubuntu-20.04
		timeout-minutes: 10
		env:
			GO_VERSION: 1.15
			GOOS: linux
			GOARCH: amd64
		steps:
			- uses: actions/checkout@v2
			- name: Go Linting
				uses: golangci/golangci-lint-action@v1.2.1
				with:
					args: --max-issues-per-linter 0 --max-same-issues 0 --out-format line-number --timeout 240s
			- name: Setup Go environment
				uses: actions/setup-go@v2.1.3
				with:
					go-version: ${{ env.GO_VERSION }}
			- name: Run tests
				run: |
					go install gotest.tools/gotestsum
					gotestsum
			- run: go vet ./...
